title: "Guru Darshan S.A"
logo: "images/Data_Analyst_Job_Description.jpg"
description: "Energetic Data Analyst passionate about turning data into actionable insights."
theme: "jekyll-theme-minimal"
additional_text: >
  ## ğŸ› ï¸ Skills
  - **Languages:** Python, SQL
  - **Tools:** Tableau, Power BI, Excel, PowerPoint
  - **Capabilities:** Data Engineering, Data Analysis, Data Visualization, Project Presentation
